import { nanoid } from "nanoid";
import { useEffect, useState } from "react";
import Page from "../components/Page";

export default function FaciltiesPage() {
  const [page, setPage] = useState(1);
  const [content, setContent] = useState([]);

  let data = [
    {
      ticketref: "TRX-000031832",
      traded_on: "08-06-2019",
      settled_on: "13-05-2019",
      name: "Greatlink Global Real Estate Corporation",
      trade_type: "Buy",
      transaction_type: "Purchase",
      currency: "SGD",
      ticker: "GELREAL_SP+23%CORP",
      quantity: 127000,
      display_quantity: 127000,
      contract_type: "FundContract",
      clickable: true,
      price: 0.788,
      settlement_amount: -100086,
      custodian: "Great Eastern Life",
      account: "Insurance",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 197,
      latest_mtm_base_ccy: null,
      running_total: -400991,
      id: 138885,
      ccy_account_id: 610,
      ccy_account_code: "demo-insurance_gelf01_sgd_01",
      user_account_id: 197,
      user_account_display: "Insurance",
      security_id: 3867,
      related_security_id: null,
    },
    {
      ticketref: "DOT-020035",
      traded_on: "06-06-2019",
      settled_on: "17-04-2019",
      name: "Gel Greatlink Global Equity",
      trade_type: "Buy",
      transaction_type: "Purchase",
      currency: "SGD",
      ticker: "GELGROW_SP",
      quantity: 130000,
      display_quantity: 130000,
      contract_type: "FundContract",
      clickable: true,
      price: 0.759,
      settlement_amount: -98699,
      custodian: "Great Eastern Life",
      account: "Insurance",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 197,
      latest_mtm_base_ccy: 38630.8,
      running_total: -300905,
      id: 19299,
      ccy_account_id: 610,
      ccy_account_code: "demo-insurance_gelf01_sgd_01",
      user_account_id: 197,
      user_account_display: "Insurance",
      security_id: 3217,
      related_security_id: null,
    },
    {
      ticketref: "TRX-000042502",
      traded_on: "08-01-2019",
      settled_on: "08-01-2019",
      name: "Apple Inc",
      trade_type: "Buy",
      transaction_type: "Purchase",
      currency: "USD",
      ticker: "AAPL_US",
      quantity: 1,
      display_quantity: 1,
      contract_type: "EquityContract",
      clickable: true,
      price: 147,
      settlement_amount: -147,
      custodian: "DBS Singapore",
      account: "dbs_fixed_income",
      bank_narration: "Testa",
      user_id: 99,
      latest_mtm_base_ccy: null,
      running_total: 261982.79,
      id: 187990,
      ccy_account_id: 380,
      ccy_account_code: "demo_fixed_income_dbsg01_usd_01",
      user_account_id: 99,
      user_account_display: "dbs_fixed_income",
      security_id: 984,
      related_security_id: null,
    },
    {
      ticketref: "TRX-000031830",
      traded_on: "13-11-2018",
      settled_on: "15-01-2014",
      name: "Greatlink Global Real Estate Corporation",
      trade_type: "Buy",
      transaction_type: "Purchase",
      currency: "SGD",
      ticker: "GELREAL_SP+23%CORP",
      quantity: 1100,
      display_quantity: 1100,
      contract_type: "FundContract",
      clickable: true,
      price: 0.8,
      settlement_amount: -100076,
      custodian: "Great Eastern Life",
      account: "Insurance",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 197,
      latest_mtm_base_ccy: null,
      running_total: -202206,
      id: 138883,
      ccy_account_id: 610,
      ccy_account_code: "demo-insurance_gelf01_sgd_01",
      user_account_id: 197,
      user_account_display: "Insurance",
      security_id: 3867,
      related_security_id: null,
    },
    {
      ticketref: "TRX-000008384",
      traded_on: "27-03-2018",
      settled_on: "27-03-2018",
      name: "USD Income",
      trade_type: "Income Received",
      transaction_type: "MiscIncome",
      currency: "USD",
      ticker: "USD_MiscIncome",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: 1500,
      custodian: "DBS Singapore",
      account: "dbs_fixed_income",
      bank_narration: "Migration Incoming Transfer Transaction",
      user_id: 99,
      latest_mtm_base_ccy: null,
      running_total: 263129.79,
      id: 115413,
      ccy_account_id: 380,
      ccy_account_code: "demo_fixed_income_dbsg01_usd_01",
      user_account_id: 99,
      user_account_display: "dbs_fixed_income",
      security_id: 17317,
      related_security_id: null,
    },
    {
      ticketref: "TRX-000008385",
      traded_on: "27-03-2018",
      settled_on: "27-03-2018",
      name: "USD Expense",
      trade_type: "Expense Incurred",
      transaction_type: "MiscExpense",
      currency: "USD",
      ticker: "USD_MiscExpense",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: -1000,
      custodian: "DBS Singapore",
      account: "dbs_fixed_income",
      bank_narration: "Simple Migration Transfer Expense",
      user_id: 99,
      latest_mtm_base_ccy: null,
      running_total: 262129.79,
      id: 115414,
      ccy_account_id: 380,
      ccy_account_code: "demo_fixed_income_dbsg01_usd_01",
      user_account_id: 99,
      user_account_display: "dbs_fixed_income",
      security_id: 17380,
      related_security_id: null,
    },
    {
      ticketref: "DAT-098107",
      traded_on: "07-04-2017",
      settled_on: "07-04-2017",
      name: "SGD MoneyFlow",
      trade_type: "Inflow",
      transaction_type: "Money In",
      currency: "SGD",
      ticker: "SGD_Money_Coming_In",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: 1000000,
      custodian: "Credit Suisse Private Banking Singapore 123",
      account: "CS00234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 101,
      latest_mtm_base_ccy: 0,
      running_total: 1000000,
      id: 96511,
      ccy_account_id: 389,
      ccy_account_code: "demo_equity_managed_cssg01_sgd_01",
      user_account_id: 101,
      user_account_display: "CS00234",
      security_id: 17238,
      related_security_id: null,
    },
    {
      ticketref: "DAT-098108",
      traded_on: "07-04-2017",
      settled_on: "07-04-2017",
      name: "SGD MoneyFlow",
      trade_type: "Inflow",
      transaction_type: "Money In",
      currency: "SGD",
      ticker: "SGD_Money_Coming_In",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: 2000000,
      custodian: "Credit Suisse Private Banking Singapore 123",
      account: "CS00234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 101,
      latest_mtm_base_ccy: 0,
      running_total: 3000000,
      id: 96512,
      ccy_account_id: 389,
      ccy_account_code: "demo_equity_managed_cssg01_sgd_01",
      user_account_id: 101,
      user_account_display: "CS00234",
      security_id: 17238,
      related_security_id: null,
    },
    {
      ticketref: "DAT-093058",
      traded_on: "25-10-2016",
      settled_on: "27-10-2016",
      name: "General Electric Co",
      trade_type: "Dividend",
      transaction_type: "Distribution",
      currency: "USD",
      ticker: "GE_US",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: true,
      price: null,
      settlement_amount: 690,
      custodian: "Deutsche Bank Singapore",
      account: "DB001234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 100,
      latest_mtm_base_ccy: 0,
      running_total: 264002.6,
      id: 91432,
      ccy_account_id: 378,
      ccy_account_code: "demo_equity_small_desg01_usd_01",
      user_account_id: 100,
      user_account_display: "DB001234",
      security_id: 17226,
      related_security_id: 3209,
    },
    {
      ticketref: "DAT-093021",
      traded_on: "19-09-2016",
      settled_on: "20-09-2016",
      name: "SGD Loan",
      trade_type: "Loan Drawdown",
      transaction_type: "Loan Create",
      currency: "SGD",
      ticker: "LoanRef_demo_fixed_income_dbsg01_sgd_01_7623625122",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: 1119038.36,
      custodian: "DBS Singapore",
      account: "dbs_fixed_income",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 99,
      latest_mtm_base_ccy: 0,
      running_total: 220652.652,
      id: 91425,
      ccy_account_id: 379,
      ccy_account_code: "demo_fixed_income_dbsg01_sgd_01",
      user_account_id: 99,
      user_account_display: "dbs_fixed_income",
      security_id: 22657,
      related_security_id: null,
    },
    {
      ticketref: "DAT-093036",
      traded_on: "19-09-2016",
      settled_on: "20-09-2016",
      name: "SGD Loan",
      trade_type: "Loan Repayment",
      transaction_type: "Loan Repay",
      currency: "SGD",
      ticker: "LoanRef_demo_fixed_income_dbsg01_sgd_01_1235876",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: -1116944.09,
      custodian: "DBS Singapore",
      account: "dbs_fixed_income",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 99,
      latest_mtm_base_ccy: 0,
      running_total: -898385.708,
      id: 91424,
      ccy_account_id: 379,
      ccy_account_code: "demo_fixed_income_dbsg01_sgd_01",
      user_account_id: 99,
      user_account_display: "dbs_fixed_income",
      security_id: 22658,
      related_security_id: null,
    },
    {
      ticketref: "DAT-093046",
      traded_on: "19-09-2016",
      settled_on: "20-09-2016",
      name: "SGD FinancingCost",
      trade_type: "Loan Interest",
      transaction_type: "Loan Cost",
      currency: "SGD",
      ticker: "LoanRef_demo_fixed_income_dbsg01_sgd_01_1235876",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: -2094.27,
      custodian: "DBS Singapore",
      account: "dbs_fixed_income",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 99,
      latest_mtm_base_ccy: 0,
      running_total: 218558.382,
      id: 91423,
      ccy_account_id: 379,
      ccy_account_code: "demo_fixed_income_dbsg01_sgd_01",
      user_account_id: 99,
      user_account_display: "dbs_fixed_income",
      security_id: 17243,
      related_security_id: 22658,
    },
    {
      ticketref: "DAT-093073",
      traded_on: "19-09-2016",
      settled_on: "21-09-2016",
      name: "Royal Dutch Shell Plc-A Shs",
      trade_type: "Dividend",
      transaction_type: "Distribution",
      currency: "EUR",
      ticker: "RDSA_NA",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: true,
      price: null,
      settlement_amount: 2423.24,
      custodian: "Credit Suisse Private Banking Singapore 123",
      account: "CS00234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 101,
      latest_mtm_base_ccy: 0,
      running_total: 73965.3899999999,
      id: 91470,
      ccy_account_id: 384,
      ccy_account_code: "demo_equity_managed_cssg01_eur_01",
      user_account_id: 101,
      user_account_display: "CS00234",
      security_id: 16040,
      related_security_id: 1091,
    },
    {
      ticketref: "DAT-093092",
      traded_on: "16-09-2016",
      settled_on: "20-09-2016",
      name: "DUKE ENERGY CORP",
      trade_type: "Dividend",
      transaction_type: "Distribution",
      currency: "USD",
      ticker: "DUK_US",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: true,
      price: null,
      settlement_amount: 1002.92,
      custodian: "Credit Suisse Private Banking Singapore 123",
      account: "CS00234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 101,
      latest_mtm_base_ccy: 0,
      running_total: 248480.97,
      id: 91469,
      ccy_account_id: 390,
      ccy_account_code: "demo_equity_managed_cssg01_usd_01",
      user_account_id: 101,
      user_account_display: "CS00234",
      security_id: 17226,
      related_security_id: 2776,
    },
    {
      ticketref: "DAT-093099",
      traded_on: "12-09-2016",
      settled_on: "14-09-2016",
      name: "CHEVRON CORP",
      trade_type: "Dividend",
      transaction_type: "Distribution",
      currency: "USD",
      ticker: "CVX_US",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: true,
      price: null,
      settlement_amount: 1861.8,
      custodian: "Credit Suisse Private Banking Singapore 123",
      account: "CS00234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 101,
      latest_mtm_base_ccy: 0,
      running_total: 247478.05,
      id: 91468,
      ccy_account_id: 390,
      ccy_account_code: "demo_equity_managed_cssg01_usd_01",
      user_account_id: 101,
      user_account_display: "CS00234",
      security_id: 17226,
      related_security_id: 4225,
    },
    {
      ticketref: "DAT-093086",
      traded_on: "09-09-2016",
      settled_on: "13-09-2016",
      name: "AMERICAN ELECTRIC POWER",
      trade_type: "Dividend",
      transaction_type: "Distribution",
      currency: "USD",
      ticker: "AEP_US",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: true,
      price: null,
      settlement_amount: 1041.6,
      custodian: "Credit Suisse Private Banking Singapore 123",
      account: "CS00234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 101,
      latest_mtm_base_ccy: 0,
      running_total: 245616.25,
      id: 91467,
      ccy_account_id: 390,
      ccy_account_code: "demo_equity_managed_cssg01_usd_01",
      user_account_id: 101,
      user_account_display: "CS00234",
      security_id: 17226,
      related_security_id: 3624,
    },
    {
      ticketref: "DAT-092916",
      traded_on: "01-09-2016",
      settled_on: "05-09-2016",
      name: "SGD MoneyFlow",
      trade_type: "Inflow",
      transaction_type: "Money In",
      currency: "SGD",
      ticker: "SGD_Money_Coming_In",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: 1850,
      custodian: "Central Provident Fund Board",
      account: "CPF",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 196,
      latest_mtm_base_ccy: 0,
      running_total: 184200,
      id: 91286,
      ccy_account_id: 608,
      ccy_account_code: "demo-cpf_cpfb01_sgd_01",
      user_account_id: 196,
      user_account_display: "CPF",
      security_id: 17238,
      related_security_id: null,
    },
    {
      ticketref: "DAT-093062",
      traded_on: "01-09-2016",
      settled_on: "05-09-2016",
      name: "PFIZER INC",
      trade_type: "Dividend",
      transaction_type: "Distribution",
      currency: "USD",
      ticker: "PFE_US",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: true,
      price: null,
      settlement_amount: 900,
      custodian: "Deutsche Bank Singapore",
      account: "DB001234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 100,
      latest_mtm_base_ccy: 0,
      running_total: 263312.6,
      id: 91431,
      ccy_account_id: 378,
      ccy_account_code: "demo_equity_small_desg01_usd_01",
      user_account_id: 100,
      user_account_display: "DB001234",
      security_id: 17226,
      related_security_id: 4334,
    },
    {
      ticketref: "DAT-093085",
      traded_on: "01-09-2016",
      settled_on: "05-09-2016",
      name: "PFIZER INC",
      trade_type: "Dividend",
      transaction_type: "Distribution",
      currency: "USD",
      ticker: "PFE_US",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: true,
      price: null,
      settlement_amount: 1800,
      custodian: "Credit Suisse Private Banking Singapore 123",
      account: "CS00234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 101,
      latest_mtm_base_ccy: 0,
      running_total: 244574.65,
      id: 91466,
      ccy_account_id: 390,
      ccy_account_code: "demo_equity_managed_cssg01_usd_01",
      user_account_id: 101,
      user_account_display: "CS00234",
      security_id: 17226,
      related_security_id: 4334,
    },
    {
      ticketref: "DAT-093095",
      traded_on: "31-08-2016",
      settled_on: "02-09-2016",
      name: "CMS ENERGY CORP",
      trade_type: "Dividend",
      transaction_type: "Distribution",
      currency: "USD",
      ticker: "CMS_US",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: true,
      price: null,
      settlement_amount: 1385.7,
      custodian: "Credit Suisse Private Banking Singapore 123",
      account: "CS00234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 101,
      latest_mtm_base_ccy: 0,
      running_total: 242774.65,
      id: 91465,
      ccy_account_id: 390,
      ccy_account_code: "demo_equity_managed_cssg01_usd_01",
      user_account_id: 101,
      user_account_display: "CS00234",
      security_id: 17226,
      related_security_id: 2119,
    },
    {
      ticketref: "DAT-093071",
      traded_on: "25-08-2016",
      settled_on: "29-08-2016",
      name: "KONINKLIJKE DSM NV",
      trade_type: "Dividend",
      transaction_type: "Distribution",
      currency: "EUR",
      ticker: "DSM_NA",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: true,
      price: null,
      settlement_amount: 2029.5,
      custodian: "Credit Suisse Private Banking Singapore 123",
      account: "CS00234",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 101,
      latest_mtm_base_ccy: 0,
      running_total: 71542.1499999999,
      id: 91464,
      ccy_account_id: 384,
      ccy_account_code: "demo_equity_managed_cssg01_eur_01",
      user_account_id: 101,
      user_account_display: "CS00234",
      security_id: 16040,
      related_security_id: 2766,
    },
    {
      ticketref: "DAT-092918",
      traded_on: "22-08-2016",
      settled_on: "24-08-2016",
      name: "SGD FinancingCost",
      trade_type: "Loan Interest",
      transaction_type: "Loan Cost",
      currency: "SGD",
      ticker: "LoanRef_demo-realestate_rere01_sgd_01_DBS30Y_BB+1.20",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: -5100,
      custodian: "Real estate",
      account: "Property",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 198,
      latest_mtm_base_ccy: 0,
      running_total: 23200,
      id: 91285,
      ccy_account_id: 612,
      ccy_account_code: "demo-realestate_rere01_sgd_01",
      user_account_id: 198,
      user_account_display: "Property",
      security_id: 17243,
      related_security_id: 19271,
    },
    {
      ticketref: "DAT-092958",
      traded_on: "22-08-2016",
      settled_on: "24-08-2016",
      name: "USD Loan",
      trade_type: "Loan Repayment",
      transaction_type: "Loan Repay",
      currency: "USD",
      ticker: "LoanRef_demo_fixed_income_dbsg01_usd_01_2939512",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: -540727.02,
      custodian: "DBS Singapore",
      account: "dbs_fixed_income",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 99,
      latest_mtm_base_ccy: 0,
      running_total: 262304.85,
      id: 91352,
      ccy_account_id: 380,
      ccy_account_code: "demo_fixed_income_dbsg01_usd_01",
      user_account_id: 99,
      user_account_display: "dbs_fixed_income",
      security_id: 22623,
      related_security_id: null,
    },
    {
      ticketref: "DAT-092967",
      traded_on: "22-08-2016",
      settled_on: "24-08-2016",
      name: "USD Loan",
      trade_type: "Loan Drawdown",
      transaction_type: "Loan Create",
      currency: "USD",
      ticker: "LoanRef_demo_fixed_income_dbsg01_usd_01_9511672",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: 541402.09,
      custodian: "DBS Singapore",
      account: "dbs_fixed_income",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 99,
      latest_mtm_base_ccy: 0,
      running_total: 803031.87,
      id: 91351,
      ccy_account_id: 380,
      ccy_account_code: "demo_fixed_income_dbsg01_usd_01",
      user_account_id: 99,
      user_account_display: "dbs_fixed_income",
      security_id: 22639,
      related_security_id: null,
    },
    {
      ticketref: "DAT-092985",
      traded_on: "22-08-2016",
      settled_on: "24-08-2016",
      name: "USD FinancingCost",
      trade_type: "Loan Interest",
      transaction_type: "Loan Cost",
      currency: "USD",
      ticker: "LoanRef_demo_fixed_income_dbsg01_usd_01_2939512",
      quantity: null,
      display_quantity: null,
      contract_type: "NonMtmContract",
      clickable: false,
      price: null,
      settlement_amount: -675.06,
      custodian: "DBS Singapore",
      account: "dbs_fixed_income",
      bank_narration:
        "Dividend Payment for DUK US PAYMENT SERVICES EDITS Equity",
      user_id: 99,
      latest_mtm_base_ccy: 0,
      running_total: 261629.79,
      id: 91353,
      ccy_account_id: 380,
      ccy_account_code: "demo_fixed_income_dbsg01_usd_01",
      user_account_id: 99,
      user_account_display: "dbs_fixed_income",
      security_id: 17237,
      related_security_id: 22623,
    },
  ];

  useEffect(() => {
    setContent([...data.slice((page - 1) * 6, page * 6)]);
  }, [page]);

  return (
    <Page>
      <h2>Facilities</h2>{" "}
      <div className="data-container">
        {content.map(function (item) {
          return (
            <div className="data-item">
              <p className="data-value">{item.ticketref}</p>
              <p className="data-value">{item.name}</p>
              <p className="data-value">{item.currency}</p>
              <p className="data-value">{item.price}</p>
            </div>
          );
        })}
        <div className="pagination">
          Page No: {page} <br />
          <button onClick={() => (page != 1 ? setPage(page - 1) : null)}>
            Previous
          </button>
          <button
            onClick={() => (page != data.length / 6 ? setPage(page + 1) : null)}
          >
            Next
          </button>
        </div>
      </div>
      <style jsx>{`
        .data-item {
          border: 1px solid #fff;
          width: 40vw;
          margin: 20px auto;
        }
      `}</style>
    </Page>
  );
}
